### ISSUE TITLE
BOM after Push to Aisler.net not correctly loaded (incompleate assignment)

### ISSUE THREAD

**Issue by calm4git** [AislerHQ/PushForKiCad#4]
After uploading a project to Aisler.net even if all parts have a perfect matching MPN, the MPN seems not to be fully matched, see screenshot
![UploadBom](https://user-images.githubusercontent.com/35043090/149493296-0a3881b8-654b-4e93-bb6f-832e1c6c5759.PNG)

After going between PCB and Parts the list gets filled up 

![UploadBom2](https://user-images.githubusercontent.com/35043090/149493353-a38a1905-4dcb-41c4-a638-24e8bae549d7.PNG)

But only leaving the project and returning to it will give the fully matches list with all known good MPSs that are in the design

![UploadBom3](https://user-images.githubusercontent.com/35043090/149493460-a0bdf2fa-f61d-4c0c-8de8-911e5397467e.PNG)

Best Regards

CalM

**Comment by tbolender** [comment]
Hi @calm4git, thanks a lot for the feedback on the BOM assigment process! We run the parts assignment in the background after upload, therefore you notice the step by step assignment as soon as you reload/return to the BOM page. I added an issue for an indicator about this to our internal development roadmap. Since it is not an issue of the KiCad plugin as such, I will close this issue for now.
